### ISSUE TITLE
Possible incorrect regex for header test

### ISSUE THREAD

**Issue by arabidopsis** [veliovgroup/spiderable-middleware#6] opened 2020-08-19 06:56 UTC
The line:

https://github.com/VeliovGroup/spiderable-middleware/blob/05078ab58400307f2acdbfeec3f56f651e5e76ac/lib/index.js#L102

should probably be:

```javascript
this.headersRE = new RegExp('^' + this.ignoredHeaders.join(strs.pipe) + '$', 'i');
```

otherwise you will match 'user-agent' for example since it has 'age' in it.

**Comment by dr-dimitru** [comment] 2020-10-02 20:18
@arabidopsis then it also should be wrapped with parentheses like

```js
new RegExp('^(' + this.ignoredHeaders.join(strs.pipe) + ')$', 'i');
```

Or I'd prefer ES6:

```js
new RegExp(`^(${this.ignoredHeaders.join(strs.pipe))$`, 'i');
```

**Comment by dr-dimitru** [comment] 2020-11-02 23:09
Hello @arabidopsis ,

Thank you a lot for reporting this one, please update to [`v1.6.2`](https://github.com/veliovgroup/spiderable-middleware/releases/tag/1.6.2)

Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment] 2020-11-20 22:31
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Closed by dr-dimitru** 2020-11-20 22:31 UTC
Labels: enhancement
